FLOW_RESULT = "(//app-flows-menu-item//ul//div//app-sublist-item/li)"
PROJECT_RESULT = "(//app-projects-menu-item//ul//div//app-sublist-item/li)"
FLOWS_BUTTON = "//div[@class='link-title' and text()='Flows']"
MY_INBOX_BUTTON = "//div[@class='link-title flex' and text()=' My Inbox ']"
PROJECT_RESULTS = "//app-projects-menu-item//app-sublist-item"
PROJECTS_BUTTON = "//div[@class='link-title' and text()='Projects']"
REPORTS_BUTTON = "//div[@class='link-title' and text()='Reports']"
SEARCH_INPUT_FLOWS = "//app-flows-menu-item//input[@type='search']"
SEARCH_INPUT_PROJECTS = "//app-projects-menu-item//input[@type='search']"
USERS_AND_GROUPS_BUTTON = "//div[@class='link-title' and text()='Users & Groups']"
NEW_FLOW_BUTTON = "//li[@class='list-submenu expanded']"
NO_DATA_MATCH_FOUND = "//label[text()='No data match found']"
CREATE_FLOW_DIALOG = "//div[@class='cdk-overlay-pane modal-panel']"
MAIN_MENU_CONTAINER = "//div[@class='full-menu overflow-full-sidenav']"
