FIRST_FLOW_RESULT = "//app-flows-menu-item//ul//div//app-sublist-item/li[1]"
FIRST_PROJECT_RESULT = "//app-projects-menu-item//ul//div//app-sublist-item/li[1]"
FLOWS_BUTTON = "//div[@class='link-title' and text()='Flows']"
MY_INBOX_BUTTON = "//div[@class='link-title flex' and text()=' My Inbox ']"
PROJECT_RESULTS = "//app-projects-menu-item//app-sublist-item"
PROJECTS_BUTTON = "//div[@class='link-title' and text()='Projects']"
REPORTS_BUTTON = "//div[@class='link-title' and text()='Reports']"
SEARCH_INPUT_FLOWS = "//app-flows-menu-item//input[@placeholder='Search all...']"
SEARCH_INPUT_PROJECTS = "//app-projects-menu-item//input[@placeholder='Search all...']"
USERS_AND_GROUPS_BUTTON = "//div[@class='link-title' and text()='Users & Groups']"
