pipeline {
  agent any
  environment {
    PYTHONPATH = "${WORKSPACE}"
    REPO_NAME = "${GIT_URL.split('/')[-2]}/${GIT_URL.split('/')[-1].replace('.git', '')}"
    USER=credentials('user')
    PASSWORD=credentials('password')
    BROWSER="remote_chrome"
    IMPLICIT_TIMEOUT="45"
  }
  stages {          
    stage('Build Browser Environments') {    
      steps {
        script {
          catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
            bat 'docker run -d -p 4444:4444 --name chrome -p 7900:7900 --shm-size="2g" selenium/standalone-chrome:latest'
          }    
        }
      }
    }
    stage('RegretionTestPC'){
      environment {
        DEVICE="pc"
      }
      steps {
        script{
          catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
            bat '.\\venv\\Scripts\\robot  --outputdir .\\Blueprint\\Reports -i ROGER .\\Blueprint\\TestCases'
          }
        }
      }
      post {
        always {
          script {
            stepName = "RegretionTestPC"
            artifactPath = "${env.WORKSPACE}\\Blueprint\\Reports\\${stepName}.html"
            archiveArtifacts artifacts: artifactPath, fingerprint: true, allowEmptyArchive: true
            bat "move .\\Blueprint\\Reports\\log.html ${artifactPath}"
          }
        }
      }
    }
  } 
  post{
    always{
      bat 'docker container stop chrome'
      bat 'docker container rm chrome'
    }
  }
}
