pipeline {
    agent any
    environment {
        DOCKERUSER='roretar' 
        DOCKERPASSWORD=credentials('dockerhubpassword')
        PYTHONPATH = "${WORKSPACE}"
        REPO_NAME = "${GIT_URL.split('/')[-2]}/${GIT_URL.split('/')[-1].replace('.git', '')}"
        PASSWORD="pasuconsumo"
        REMOTE_URL="http://0.0.0.0:4444"
        USER="roger.renjifo"
        BROWSER="remote_chrome"
        DEVICE="pc"
        DRIVER_PATH="./"
        IMPLICIT_TIMEOUT="20"
    }
    stages {
        stage('Build Browser Environments') {
            steps {
                sh 'pwd'
                sh 'ls'
            }
        }
        stage('Run Test Cases'){
            agent{
                docker{
                    image 'roretar/gui-blueprint-environment:1.0.0'
                    args '--net grid'
                }
            }
            steps {
                sh 'echo "run the browser containers."'
                sh 'robot -i ADD_COMPONENTS Blueprint/TestCases'
                sh 'pwd'
                sh 'pip list'  
            }
            post {
                always {
                    archiveArtifacts artifacts: 'reports', fingerprint: true
                }
            }
        }
        stage('Down Browser Environments') {
            steps {
                sh 'pwd'
                sh 'docker container ls'
                sh 'ls'
            }
        }
    }
    post{
        always{
            sh 'ls '
        }
    }
}
