pipeline {
  agent any
  stages{
    stage('Code Inspection'){
      steps{
        bat 'echo Test stage'
      }
    }
    stage('Instalar dependencias') {
      steps {
        script {
          virtualenvDir = "${WORKSPACE}\\venv"  // Directorio del entorno virtual
          bat "python -m venv ${virtualenvDir}"  // Crear el entorno virtual
          bat "${virtualenvDir}\\Scripts\\pip install -r ${WORKSPACE}\\requeriments.txt"  // Instalar las dependencias en el entorno virtual
          bat ".\\venv\\Scripts\\activate"
        }
      }
    }
    stage('Test'){
      steps{
        bat 'python --help'
        bat '.\\venv\\Scripts\\robot  --outputdir .\\Blueprint/Reports -i PROJECT_PAGE .\\Blueprint/TestCases'
      }
    }
  }
}
