pipeline {
  agent any
  environment {
    PYTHONPATH = "${WORKSPACE}\\"
    PASSWORD=credentials('PASSWORD')
    USER="rocío.morales"
    BROWSER="chrome"
    DEVICE="pc"
    DRIVER_PATH=".\\"
    IMPLICIT_TIMEOUT="20"
    CI_EXECUTION="True"
  }
  stages{
    stage('Code Inspection'){
      steps{
        bat 'echo Test stage'
      }
    }
    stage('Instalar dependencias') {
      steps {
        script {
          virtualenvDir = "${WORKSPACE}\\venv"  // Directorio del entorno virtual
          bat "python -m venv ${virtualenvDir}"  // Crear el entorno virtual
          bat "${virtualenvDir}\\Scripts\\pip install -r ${WORKSPACE}\\requeriments.txt"  // Instalar las dependencias en el entorno virtual
          bat ".\\venv\\Scripts\\activate"
        }
      }
    }
    stage('Test'){
      steps{
        bat '.\\venv\\Scripts\\robot  --outputdir .\\Blueprint\\Reports -i PROJECT_PAGE .\\Blueprint\\TestCases'
      }
    }
  }
}
