CANCEL_DIALOG_BUTTON="//button[contains(@class,'secondary')]"
DELETE_DIALOG_BUTTON="//button[contains(@class,'primary')]"
CLOSE_DIALOG_BUTTON="close-modal-button"
DIALOG_TITLE="//div[@class='modal-body']//child::*[self::h2 or self::h3]"
DIALOG_QUESTION="(//div[@class='modal-body']//child::*[self::div or self::p])[2]"
FATHER_DIALOG_CONTAINER = "//div[@class='cdk-overlay-container']"
