CANCEL_DIALOG_BUTTON="//button[@class='secondary-button action']"
DELETE_DIALOG_BUTTON="//button[@class='primary-button action']"
CLOSE_DIALOG_BUTTON="close-modal-button"
DIALOG_TITLE="//div[@class='modal-body']//child::*[self::h2 or self::h3]"
DIALOG_QUESTION="(//div[@class='modal-body']//child::*[self::div or self::p])[2]"
