FIELD_LOCATOR = "//span[@title = '<<value>>']//following::label[1]"
MULTILINE_FIELD_LOCATOR = "//span[@title = '<<value>>']//following::textarea[1]"
EDIT_BUTTON_LOCATOR = "//span[@title = '<<value>>']//following::button[1]"
SAVE_BUTTON_LOCATOR = "//button[@title = 'Save']"
CANCEL_BUTTON_LOCATOR = "//button[@title = 'Cancel']"
CLEAR_ALL_DROPDOWN_BUTTON = "//span[@title = 'Clear all']"
CHECKBOX_LABEL_LOCATOR = "//span[@title = '<<value>>']//following::span[@class='label']"
SELECT_DATE_INPUT_LOCATOR = "//div[@class= 'date-picker-input']"
DELETE_DATE_BUTTON_LOCATOR = "//img[@title= 'Clear All']"
CALENDAR_DATE_BUTTON_LOCATOR = "//img[@title= 'Calendar']"
USER_LIST_EMAIL_BUTTON_LOCATOR = "//span[@title = '<<value>>']//following::a[@title= 'Mail'][1]"
DROPDOWN_OPTION_LOCATOR = "//span[text() = '<<value>>' and @class = 'ng-option-label']"
USERLIST_DROPDOWN_OPTION_LOCATOR = "//span[@title= '<<value>>']"
EDITABLE_TEXT_INPUT_LOCATOR = "//input[@type= 'text']"
EDITABLE_NUMBER_INPUT_LOCATOR = "//input[@type= 'number']"
EDITABLE_MULTILINE_INPUT_LOCATOR = "//div[@class = 'edit-mode multiline-textarea']//child::textarea"
