SYSTEM_TITLE = "//h3[normalize-space()='System']"
LABEL_CURRENT_STEP = "//span[normalize-space()='Current step']"
CURRENT_STEP_VALUE = "(//div[@class='system']/descendant::label)[1]"
EDIT_CURRENT_STEP = "(//div[@class='system']/descendant::button)[1]"
LABEL_ACTION_OWNER = "//span[normalize-space()='Action owner']"
ACTION_OWNER_VALUE = "(//div[@class='system']/descendant::label)[2]"
NONE_ACTION_OWNER = "//span[normalize-space()='Action owner']/parent::div/child::div/child::span"
FIELD_REQUIRED_OWNER = "//span[normalize-space()='Action owner']/parent::div/child::div/child::div/child::span"
EDIT_ACTION_OWNER = "(//div[@class='system']/descendant::button)[2]"
LABEL_CREATION_DATE = "//span[normalize-space()='Creation date']"
CREATION_DATE_VALUE = "//span[normalize-space()='Creation date']/parent::div/child::div/child::span"
LABEL_LAST_UPDATE = "//span[normalize-space()='Last update']"
LAST_UPDATE_VALUE = "//span[normalize-space()='Last update']/parent::div/child::div/child::span"
LABEL_CLOSURE_DATE = "//span[normalize-space()='Closure date']"
CLOSURE_DATE_VALUE = "//span[normalize-space()='Closure date']/parent::div/child::div/child::span"
SAVE_LOCATOR = "(//div[@class='edit-buttons-container']/descendant::button)[2]"
CANCEL_LOCATOR = "(//div[@class='edit-buttons-container']/descendant::button)[2]"
FIELD_REQUIRED = "//div[contains(@class, 'text-formError')]"
