CREATE_BUTTON = "//button[@class='bp-btn-action']"
TEMPLATE_TITLE = "//h2[@title='<<template_title>>']"
CHECKBOX = "//h3[@title='<<section_name>>']//following-sibling::div//descendant::label[@title='<<label_name>>']"
TEXT_USER_NUMBER_DATE_BOX = "//h3[@title='<<section_name>>']//following-sibling::div//descendant::label[@title='<<label_name>>']//following-sibling::div//child::input"
SELECT_USER = "//span[@title='<<user>>'] | //label[@title='<<user>>']"
REMOVE_USER_LOCATOR= "//h3[@title='<<section_name>>']//following-sibling::div//descendant::label[@title='<<label_name>>']//following-sibling::div//descendant::span[@title='Clear all']"
