CREATE_BUTTON = "//button[@class='bp-btn-action']"
TEMPLATE_TITLE = "//h2[@class='overflow-project-instance']"
CHECKBOX = "//h3[@title='<<section_name>>']//following-sibling::div//descendant::label[@title='<<label_name>>']"
TEXT_USER_NUMBER_DATE_BOX = "//h3[@title='<<section_name>>']//following-sibling::div//descendant::label[@title='<<label_name>>']//following-sibling::div//child::input"
SELECT_USER = "//span[@title='<<user>>'] | //label[@title='<<user>>'] | //div[@title='<<user>>']"
REMOVE_USER_LOCATOR = "//h3[@title='<<section_name>>']//following-sibling::div//descendant::label[@title='<<label_name>>']//following-sibling::div//descendant::span[@title='Clear all']"
CREATE_BUTTON_CSS_SELECTOR = ".bp-btn-action:not([disabled])"
FIELD_REQUIRED_ERROR_MESSAGE_LOCATOR = "//span[contains(text(), ' Field Required ')]"
ERROR_MESSAGE_ICON = "//app-warning-error-icon"
LABEL_LOCATOR = "//h3[@title='<<section_name>>']//following-sibling::div//descendant::label[@title='<<label_name>>']"
TEXT_IN_DROPDOWN = "//h3[@title='<<section_name>>']//following-sibling::div//descendant::label[@title='<<label_name>>']//following-sibling::div//child::span[@class='ng-value-label']"
LIST_OPTIONS_DROPDOWN = "//div[@class='ng-dropdown-panel-items scroll-host']"
