EXPORT_DIALOG = "//app-export-csv"
EXPORT_DIALOG_CLOSE_BUTTON = "//app-export-csv//descendant::button[@class='close-modal-button']"
EXPORT_DIALOG_TITLE = "//app-export-csv//descendant::h3"
EXPORT_DIALOG_INPUT = "//app-export-csv//descendant::input[@name='name']"
EXPORT_DIALOG_INPUT_LABEL = "//app-export-csv//descendant::label[@for='name']"
EXPORT_DIALOG_CANCEL_BUTTON = "//app-export-csv//descendant::button[normalize-space()='Cancel']"
EXPORT_DIALOG_BUTTON = "//app-export-csv//descendant::button[normalize-space()='Export']"
