INPUT_SEARCH_GROUPS = "//input[@placeholder='Search groups']"
GROUP_RESULT = "(//div[@class='container-columns'][1]//button[@class='group-button'])"
GROUP_RESULT_DROPDOWN_MENU = "(//button[@id='section-dropdown'])"
GROUP_RESULT_EDIT_BUTTON = "(//div[@class='dropdown-item item'][normalize-space()='Edit'])"
GROUP_RESULT_DELETE_BUTTON = "(//div[@class='dropdown-item item'][normalize-space()='Delete'])"
NEW_GROUP_BUTTON = "//button[@class='new-button'][normalize-space()='New'][1]"
INPUT_GROUP_NAME = "//input[@formcontrolname='name']"
CANCEL_CREATE_GROUP_BUTTON = "//button[@class='secondary-button action']"
CREATE_GROUP_BUTTON = "//button[@class='primary-button action']"
