INPUT_SEARCH_GROUPS = "//input[@placeholder='Search groups']"
FIRST_GROUP_RESULT = "//div[@class='container-columns'][1]//button[@class='group-button']"
FIRST_GROUP_RESULT_DROPDOWN_MENU = "//div[@class='container-columns'][1]//button[@id='section-dropdown']"
FIRST_GROUP_RESULT_EDIT_BUTTON = "(//div[@class='dropdown-item item'][normalize-space()='Edit'])[1]"
FIRST_GROUP_RESULT_DELETE_BUTTON = "(//div[@class='dropdown-item item'][normalize-space()='Delete'])[1]"
NEW_GROUP_BUTTON = "(//button[@class='new-button'][normalize-space()='New'])[1]"
INPUT_GROUP_NAME = "(//input[@placeholder='e.g. My group name'])"
CANCEL_CREATE_GROUP_BUTTON = "(//button[normalize-space()='Cancel'])"
CREATE_GROUP_BUTTON = "(//button[normalize-space()='Create'])[1]"
