SECTION_LOCATOR = "//h2[text()=' ToChange ']//following::div[4]"
SECTION_TITLE_LOCATOR = "//div[@id='section']//h2"
SECTION_DROPDOWN_LOCATOR = "//h2[text()=' ToChange ']//following::button[1]"
SECTION_DELETE_BUTTON_LOCATOR = "//div[@data-popper-placement='right']"
SECTION_ERROR_MESSAGE_LOCATOR = "//h2[text()=' ToChange ']//following-sibling::span"
COMPONENT_TITLE_LOCATOR = "//input[@id='ToChange']//preceding::label[1]"
COMPONENT_DROPDOWN_LOCATOR = "//input[@id='ToChange']//following::button[1]"
COMPONENT_DELETE_BUTTON_LOCATOR = "//input[@id='ToChange']//following::button[1]//following-sibling::div"
