SECTION_NAME_INPUT_LOCATOR = "//input[@name='sectionNameControl']"
NAME_INPUT_LOCATOR = "//label[text()='Name']//following::input[1]"
PLACEHOLDER_INPUT_LOCATOR = "//label[text()='Placeholder']//following::input[1]"
DEFAULT_VALUE_INPUT_LOCATOR = "//label[text()='Default Value']//following::input[1]"
FIELD_TYPE_SELECT_LOCATOR = "//ng-select[@id='fieldType']"
FIELD_TYPE_SELECT_OPTION_LOCATOR = "//span[@class='ng-option-label' and text()='<<value>>']"
REQUIRED_FIELD_LABEL_LOCATOR = "//label[text()=' Required field ']"
NUMBER_FORMAT_SELECT_LOCATOR = "//label[text()='Format']//following::ng-select"
NUMBER_DEFAULT_VALUE_FORMATTED_NOEDIT_LOCATOR = "//label[text()='Default Value Formatted']//following::input[1]"
CHECKBOX_DEFAULT_CHECKED_LABEL_LOCATOR = "//label[text()='Default Checked']"
DATE_DEFAULT_YEAR_OPTION_LOCATOR = "//div[@class='item-container selected' or @class='item-container']//child::a[text()=' <<value>> ']"
DATE_DEFAULT_MONTH_OPTION_LOCATOR = "//div[@class='item-container selected' or @class='item-container']//child::a[text()=' <<value>> ']"
DATE_DEFAULT_DAY_OPTION_LOCATOR = "//div[@class='calendar-table-cell' and text()=' <<value>> ']"
DATE_FORMAT_SELECT_LOCATOR = "//label[text()='Format']//following::ng-select"
ADD_DROPDOWN_VALUE_INPUT_LOCATOR = "//label[text()=' Dropdown values ']//following::input[1]"
ADD_DROPDOWN_VALUE_BUTTON_LOCATOR = "//label[text()=' Dropdown values ']//following::button"
ADDED_DROPDOWN_VALUE_LOCATOR = "//p[@title='<<value>>']"
ADDED_DROPDOWN_VALUE_DELETE_BUTTON_LOCATOR = "//p[@title='<<value>>']//following::button[1]"
DROPDOWN_VALUES_NOEDIT_LOCATOR = "//label[text()=' Dropdown values ']//following::ng-select[1]"
DEFAULT_VALUE_SELECT_LOCATOR = "//label[text()='Default Value']//following::ng-select"
DEFAULT_VALUE_SELECT_OPTION_LOCATOR = "//div[@class='selectable-overflow-full' and text()=' <<value>> ']"
USERLIST_VALUES_SELECT_LOCATOR = "//label[text()='User List values']//following::ng-select[1]"
DEFAULT_DATE_YEAR_SELECT_LOCATOR = "//div[@class='calendar-header']//child::div[@class='dropdown-selector'][2]"
DEFAULT_DATE_MONTH_SELECT_LOCATOR = "//div[@class='calendar-header']//child::div[@class='dropdown-selector'][1]"
USERLIST_VALUE_LOCATOR = "//span[@title='<<value>>']"
USERLIST_DEFAULT_VALUE_OPTION_LOCATOR = "//span[@class='ng-option-label' and text()='<<value>>']"
