SECTION_NAME_INPUT_LOCATOR = "//input[@name='sectionNameControl']"
NAME_INPUT_LOCATOR = "//label[text()='Name']//following::input[1]"
PLACEHOLDER_INPUT_LOCATOR = "//label[text()='Placeholder']//following::input[1]"
DEFAULT_VALUE_INPUT_LOCATOR = "//label[text()='Default Value']//following::input[1]"
FIELD_TYPE_SELECT_LOCATOR = "//ng-select[@id='fieldType']"
REQUIRED_FIELD_LABEL_LOCATOR = "//label[text()=' Required field ']"
NUMBER_FORMAT_SELECT_LOCATOR = "//label[text()='Format']//following::ng-select"
NUMBER_DEFAULT_VALUE_FORMATTED_NOEDIT_LOCATOR = "//label[text()='Default Value Formatted']//following::input[1]"
CHECKBOX_DEFAULT_CHECKED_LABEL_LOCATOR = "//label[text()='Default Checked']"
DATE_FORMAT_SELECT_LOCATOR = "//label[text()='Format']//following::ng-select"
ADD_DROPDOWN_VALUE_INPUT_LOCATOR = "//label[text()=' Dropdown values ']//following::input[1]"
ADD_DROPDOWN_VALUE_BUTTON_LOCATOR = "//label[text()=' Dropdown values ']//following::button"
DROPDOWN_VALUES_NOEDIT_LOCATOR = "//label[text()=' Dropdown values ']//following::ng-select[1]"
DEFAULT_VALUE_SELECT_LOCATOR = "//label[text()='Default Value']//following::ng-select"
USERLIST_VALUES_SELECT_LOCATOR = "//label[text()='User List values']//following::ng-select[1]"
