INPUT_TEXT_ELEMENT = "//div[@id='form__field__options']//child::app-toolbox-option[1]"
INPUT_DATE_ELEMENT = "//div[@id='form__field__options']//child::app-toolbox-option[2]"
INPUT_DROPDOWN_ELEMENT = "//div[@id='form__field__options']//child::app-toolbox-option[3]"
INPUT_MULTILINE_ELEMENT = "//div[@id='form__field__options']//child::app-toolbox-option[4]"
INPUT_NUMBERS_ELEMENT = "//div[@id='form__field__options']//child::app-toolbox-option[5]"
INPUT_USER_LIST_ELEMENT = "//div[@id='form__field__options']//child::app-toolbox-option[6]"
INPUT_CHECKBOX_ELEMENT = "//div[@id='form__field__options']//child::app-toolbox-option[7]"
SECTION_ELEMENT = "//div[@id='section__options']//descendant::div[contains(@class, 'panel-button-container')]"
COMPONENTS_TITLE = "//app-form-field-options//preceding::div[contains(@class, 'panel-text-vertical-spacer')]"
SECTION_TITLE = "//app-section-options//preceding::div[contains(@class,'panel-text-vertical-spacer')][1]"
DROP_AREA = "//*[@id='drop__area']"
