FIRST_ID = "first"
START_ID = "start"
COMPONENT_LIST_XPATH = "//div[contains(@class, 'process-element')]"
DOTS_BUTTON_XPATH = "//div[@id='<<data>>']/descendant::button"
DELETE_BUTTON_XPATH = "//div[@id='<<data>>']/descendant::div[5]"
CLONE_BUTTON_XPATH = "//div[@id='<<data>>']/descendant::div[4]"
CONECTOR_XPATH = "//div[contains(@class,'endpoint<<data>>')][<<number>>]"
DOT_START = "//div[@class='jtk-endpoint jtk-endpoint-connected jtk-endpoint-full']"
MENU_DROPDOWN = "//div[@class='shadow-md dropdown-menu show']"
