TITLE_FLOW_PERMISSIONS = "//section[@class='permission-section']//h2"
TITLE_ALL_VERSIONS = "//section[@class='permission-section']//p"
SUBTITLE_FLOW_ADMIN = "//div[contains(@class, 'flex gap')]//label"
EMPTY_DROPDOWNBOX_MESSAGE = "//span[contains(@class, 'permission-select-error-message')]"
DROPDOWNBOX = "(//span[@class='ng-arrow-wrapper'])[1]"
SAVE_BUTTON = "//button[contains(@class, 'bp-btn-action-lightgreen h')]"
SCROLL_BAR = "//div[@class='ng-dropdown-panel-items scroll-host']"
PERMISSIONS_TAB = "//main[text()=' Permissions ']"
