COMPONENTS_TITLE = "//div[@class='panel-text-vertical-spacer']"
STEP_LOCATOR = "(//div[@class='cdk-drag panel-button-container'])[1]"
ACTION_LOCATOR = "(//div[@class='cdk-drag panel-button-container'])[2]"
CANVAS_LOCATOR = "//div[@id='canvas']"
MAIN_CONTAINER_LOCATOR = "//div[@class='main-container-outlet']"
MAIN_MENU_LOCATOR = "//div[@class='main-container-menu']"
PANEL_RIGHT_LOCATOR = "//div[@class='panel-right-border']"
HEADER_LOCATOR = "//*[@class='w-full']"
PROPERTIES_LOCATOR = "//*[@class='col-span-3 row-span-full flex justify-center relative']"
PROPERTIES_TITLE_LOCATOR = "//h2[@class='name overflow-properties-panel']"
