DROP_DOWN_FLOW_MENU = "//app-flows-menu-item//button[@class='title-arrow']"
NEW_FLOW_BUTTON = "//li[@class='list-submenu expanded']"
HEADER_CREATE_NEW_FLOW = "//h3[@class='modal-title' and text()='Create Flow']"
INPUT_NEW_FLOW_NAME = "//input[@name='name']"
INPUT_NEW_FLOW_CODE = "//input[@name='code']"
LABEL_NAME = "//label[@class='modal-field-label' and text()='Name']"
LABEL_CODE = "//label[@class='modal-field-label' and text()='Code']"
CANCEL_NEW_FLOW_BUTTON = "//button[@class='secondary-button action']"
CREATE_NEW_FLOW_BUTTON = "//button[@class='primary-button action']"
NAME_FIELD_REQUIRED_MESSAGE = "//input[@formcontrolname='name']/following-sibling::span"
CODE_FIELD_REQUIRED_MESSAGE = "//input[@formcontrolname='code']/following-sibling::span"
