TITLE_FLOW_PERMISSIONS = "//h2[text()='Flow Permissions']"
TITLE_ALL_VERSIONS = "//p[text()='(all versions)']"
SUBTITLE_FLOW_ADMIN = "//label[text()=' Flow Admin ']"
EMPTY_DROPDOWNBOX_MESSAGE = "//span[contains(@class, 'permission-select-error-message')]"
DROPDOWNBOX = "(//span[@class='ng-arrow-wrapper'])[1]"
SAVE_BUTTON = "//button[@class='bp-btn-action-lightgreen h-9']"
SCROLL_BAR = "//div[@class='ng-dropdown-panel-items scroll-host']"
PERMISSIONS_BUTTON = "//main[text()=' Permissions ']"
