STATUS="//span[contains(@class,'uppercase bg-primary')][1]"
VERSION="//span[contains(@class,'uppercase bg-primary')][2]"
FLOW_NAME="//p[@class='text-2xl overflow-stepper-header']"
FLOW_DROPDOWN="//button[contains(@class,'outline-none focus:outline-none')]"
DELETE="//button[@class='w-full flex']"
SELECT_VERSION="//button[@class='w-full text-left flex items-center']"
VERSIONS_LIST="//ul[contains(@class,'my-1')]"
VERSIONS="//button[@class='text-left overflow-version-item w-full' and contains(text(),'<<value>>')]"
LAST_UPDATED_TEXT="//span[@class='text-xs text-black italic mr-1']"
SAVE_BUTTON="bp-btn-action"
SAVE_NEXT_BUTTON="bp-btn-action-lightgreen"
BAR_TAB="//header[contains(@class,'relative mb-2')]//following-sibling::main[contains(text(),'TAB_NAME')]"
ICON_TAB="//main[contains(text(),'TAB_NAME')]//span[contains(@class,'icon')]"
BAR_TAB_MARKED="//main[contains(text(),'TAB_NAME')]//preceding::header[@class='relative mb-2 bg-primary']"
ICON_TAB_MARKED="//main[contains(text(),'TAB_NAME')]//span[@class='icon bg-primary']"
ICON_ERROR_MARKED="//main[contains(text(),'TAB_NAME')]//span[@class='icon bg-formError bg-primary']"
BAR_TAB_UNMARKED="//main[contains(text(),'TAB_NAME')]//preceding::header[@class='relative mb-2 bg-gray-300']"
ICON_TAB_UNMARKED="//main[contains(text(),'TAB_NAME')]//span[@class='icon bg-gray-300']"
ICON_ERROR_UNMARKED="//main[contains(text(),'TAB_NAME')]//span[@class='icon bg-formError bg-gray-300']"
