STATUS="//span[@class='uppercase bg-primary text-white rounded-md p-1 text-xs'][1]"
VERSION="//span[@class='uppercase bg-primary text-white rounded-md p-1 text-xs'][2]"
FLOW_NAME="text-2xl overflow-stepper-header"
FLOW_DROPDOWN="outline-none focus:outline-none border-none bg-none rounded-md flex items-center hover:bg-white hover:cursor-pointer p-2"
DELETE="w-full flex"
SELECT_VERSION="w-full text-left flex items-center"
VERSIONS="//button[@class='text-left overflow-version-item w-full' and contains(text(),'v1')]"
UPDATE_TEXT="text-xs text-black italic mr-1"
SAVE_BUTTON="bp-btn-action"
SAVE_NEXT_BUTTON="bp-btn-action-lightgreen"
BAR_TAB_MARKED="//main[contains(text(),'TAB_NAME')]//preceding::header[@class='relative mb-2 bg-primary']"
ICON_TAB_MARKED="//main[contains(text(),'TAB_NAME')]//span[@class='icon bg-primary']"
ICON_ERROR_MARKED="//main[contains(text(),'TAB_NAME')]//span[@class='icon bg-formError bg-primary']"
BAR_TAB_UNMARKED="//main[contains(text(),'TAB_NAME')]//preceding::header[@class='relative mb-2 bg-gray-300']"
ICON_TAB_UNMARKED="//main[contains(text(),'TAB_NAME')]//span[@class='icon bg-gray-300']"
ICON_ERROR_UNMARKED="//main[contains(text(),'TAB_NAME')]//span[@class='icon bg-formError bg-gray-300']"
