TITLE_FLOW_PERMISSIONS = "//section[@class='permission-section']//h2"
TITLE_ALL_VERSIONS = "//section[@class='permission-section']//p"
TITLE_PROCESS_PERMISSIONS = "//h2[@_ngcontent-yos-c158='']"
TITLE_CURRENT_VERSION = "//p[text() = '(all versions)']"
TITLE_SECTION_VISIBILITY = "//h3[text() = 'Sections Visibility']/ancestor::section[1]/h3"
