TITLE_FLOW_PERMISSIONS = "//section[@class='permission-section']//h2"
TITLE_ALL_VERSIONS = "//section[@class='permission-section']//p"
TITLE_PROCESS_PERMISSIONS = "(//div[@class='section-title'])[2]/h2"
TITLE_CURRENT_VERSION = "(//div[@class='section-title'])[2]/p"
TITLE_SECTION_VISIBILITY = "//h3[text()='Sections Visibility']/ancestor::section[1]/h3"
