TITLE_PROCESS_PERMISSIONS = "//h2[@_ngcontent-yos-c158='']"
TITLE_CURRENT_VERSION = "//p[text() = '(all versions)']"
TITLE_SECTION_VISIBILITY = "//h3[text() = 'Sections Visibility']/ancestor::section[1]/h3"
SUBTITLE_INITIATE_PROCESS = "//label[@_ngcontent-yos-c155='' and @for='initiate-process']"
EMPTY_DROPDOWNBOX_TEXT ="//div[@class='ng-input']/descendant::input[@id='initiate-process']"
DROPDOWNBOX_NARROW = "//span[@class='ng-arrow-wraper']"
DROPDOWNBOX_INITIATE_PROCESS = "//div[@class='ng-select-container ng-has-value']"
SCROLL_BAR = "//*[@id='a83895dc546a']/div"
DROPDOWNBOX_SECTIONS_VISIBILITY  = "//div[contains(@class,'sections')]//ng-select[@id='<<component_number>>']"
